export const GET_INITIAL_BEER_LIST = 'GET_INITIAL_BEER_LIST';
export const GET_INITIAL_BEER_LIST_SUCCESS = 'GET_INITIAL_BEER_LIST_SUCCESS';
export const GET_INITIAL_BEER_LIST_FAILURE = 'GET_INITIAL_BEER_LIST_FAILURE';

export const GET_BEER_LIST_ANOTHER_PAGE = 'GET_BEER_LIST_ANOTHER_PAGE';
export const GET_BEER_LIST_ANOTHER_PAGE_SUCCESS = 'GET_BEER_LIST_ANOTHER_PAGE_SUCCESS';
export const GET_BEER_LIST_ANOTHER_PAGE_FAILURE = 'GET_BEER_LIST_ANOTHER_PAGE_FAILURE';

export const GET_SIMILAR_BEERS = 'GET_SIMILAR_BEERS'
export const GET_SIMILAR_BEERS_SUCCESS = 'GET_SIMILAR_BEERS_SUCCESS'
export const GET_SIMILAR_BEERS_FAILURE = 'GET_SIMILAR_BEERS_FAILURE'

export const INCREASE_PAGE_COUNT = 'INCREASE_PAGE_COUNT';
export const RESET_PAGE_COUNT = 'RESET_PAGE_COUNT';
