export const GET_INITIAL_BEER_LIST = 'GET_INITIAL_BEER_LIST';
export const GET_INITIAL_BEER_LIST_SUCCESS = 'GET_INITIAL_BEER_LIST_SUCCESS';
export const GET_INITIAL_BEER_LIST_FAILURE = 'GET_INITIAL_BEER_LIST_FAILURE';

export const GET_BEER_LIST_ANOTHER_PAGE = 'GET_BEER_LIST_ANOTHER_PAGE';
export const GET_BEER_LIST_ANOTHER_PAGE_SUCCESS = 'GET_BEER_LIST_ANOTHER_PAGE_SUCCESS';
export const GET_BEER_LIST_ANOTHER_PAGE_FAILURE = 'GET_BEER_LIST_ANOTHER_PAGE_FAILURE';
